##################################################################################################
# Comments service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comments
---
apiVersion: v1
kind: Service
metadata:
  name: comments
  labels:
    app: comments
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: comments
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: comments-v1
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: comments
        version: v1
    spec:
      serviceAccountName: comments
      containers:
        - name: comments
          image: docker.io/ilackarms/comments:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          args: ['--fail-half']